### ISSUE TITLE
plugin isn't working for me

### ISSUE THREAD

**Issue by axeheadfloats** [billerickson/Display-Posts-Pagination#1]
The plugin doesn't seem to be working for me. The pagination shows up at the bottom and selecting the links changes the url to something like this: url/pagination-test/?dps_paged=4  (for page 4).

But the list doesn't change whatever nav links I press. The shortcode I have used is: [display-posts posts_per_page="3" pagination="true"  include_excerpt="true" wrapper="ol" include_title="true" image_size="medium" offset="1" post_type="clo-events" include_link="false"].

I guess I should try this on a new install (make sure I haven't created any conflicts) but I wondered if you're having any issues with this or have any advice. This would be _very_ helpful for what I'm currently working on.

Thanks!

**Comment by billerickson** [comment]
Unfortunately offset does not work with pagination. If you use an offset, it overrides any pagination setting. 

If you drop the offset parameter it should work for you.

**Comment by axeheadfloats** [comment]
Awesome. Thanks! 

--
*Joshua Ginter*
mail@JGinter.me
(m) 708-297-0326
