### ISSUE TITLE
Where do I put the extension?

### ISSUE THREAD

**Issue by wmodes** [billerickson/Display-Posts-Pagination#2]
Hi Bill,

It's not clear from your Display-Posts-Pagination docs where Display Posts expects to find this extension. Where should it be placed?

I tried putting it in my theme directory, which seemed like the most reasonable place since updating the theme would kill it if I dropped it into the plugin directory. But no dice.

Then I tried putting the extension in the display-posts-shortcode plugin directory, but it still didn't offer any pagination.

Do you have some guidance?

**Comment by billerickson** [comment]
Display Posts Pagination is a WordPress plugin that extends the functionality of Display Posts. 

You can go to Plugins > Add New and click "Upload Plugin" at the top, then upload the zip file. Activate it like any other plugin.

Once installed, it will add pagination when you add pagination="true" to shorcodes:

```
[display-posts pagination="true"]
```
