### ISSUE TITLE
Make pagination true by default. 

### ISSUE THREAD

**Issue by alex-gav** [billerickson/Display-Posts-Pagination#3]
It would be grate to be able to have the pagination ON by default and have parameter to turn it off.

Thanks for grate plugin!

**Comment by billerickson** [comment]
I agree, that's a good idea, but unfortunately I can't implement it now because it will change the functionality for all existing users of the plugin.

Here's a tutorial on how to [change the default attributes in Display Posts](https://displayposts.com/2019/01/04/change-default-attributes/).

Add this code to your theme's functions.php file or a core functionality plugin to turn pagination on by default:

```
/**
 * Set Defaults in Display Posts Shortcode
 * @see https://displayposts.com/2019/01/04/change-default-attributes/
 *
 * @param array $out, the output array of shortcode attributes (after user-defined and defaults have been combined)
 * @param array $pairs, the supported attributes and their defaults
 * @param array $atts, the user defined shortcode attributes
 * @return array $out, modified output
 */
function be_dps_defaults( $out, $pairs, $atts ) {
	$new_defaults = array( 
		'pagination' => true,
	);
	
	foreach( $new_defaults as $name => $default ) {
		if( array_key_exists( $name, $atts ) )
			$out[$name] = $atts[$name];
		else
			$out[$name] = $default;
	}
	
	return $out;
}
add_filter( 'shortcode_atts_display-posts', 'be_dps_defaults', 10, 3 );
```

**Comment by alex-gav** [comment]
Unfortunately this is not working. I have tried this, but this is working only for parameters of the main Display Posts plugin.

**Comment by billerickson** [comment]
Hmm, it looks like you're right.

In that case, I recommend you make the following tweaks to the `display-posts-plugin.php` file:

At the top ([line 6](https://github.com/billerickson/Display-Posts-Pagination/blob/master/display-posts-pagination.php#L6)) change `Version: 1.0.0` to `Version 99.0.0`. This will ensure your version is never overwritten by a release I do in the future.

At the top of the two functions ([lines 24-25](https://github.com/billerickson/Display-Posts-Pagination/blob/master/display-posts-pagination.php#L24-L25) and [lines 69-70](https://github.com/billerickson/Display-Posts-Pagination/blob/master/display-posts-pagination.php#L69-L70)), change this:

```
if( empty( $atts['pagination'] ) )
	return $output;
```

To this:

```
if( !empty( $atts['pagination'] ) && false === filter_var( $atts['pagination'], FILTER_VALIDATE_BOOLEAN ) )
	return $output;
```

**Comment by alex-gav** [comment]
Thanks, but I prefer to have updates available. I will change all shortcodes I use. Probably the issue with default parameters should be fixed in main plugin.

Thanks again!
