### ISSUE TITLE
Do not work if you use the display as table snippet

### ISSUE THREAD

**Issue by bicho44** [billerickson/Display-Posts-Pagination#4]
Hi:

I'm trying to use the plug-in with the "display as a table" snippet, but its seems to doesn't work, the table display ok, but not the pagination.

Maybe i need to add another parameter to the short code?

Best regards from Patagonia Argentina

**Comment by billerickson** [comment]
The [display results as a table tutorial](https://displayposts.com/2019/03/18/display-results-as-a-table/) replaces the opening and closing output with the table markup, so any other extension that adds content to the start/end would be affected. 

Try changing this line:

```
add_filter( 'display_posts_shortcode_wrapper_close', array( $this, 'layout_editors_choice_close' ), 10, 2 );
```

To this:

```
add_filter( 'display_posts_shortcode_wrapper_close', array( $this, 'layout_editors_choice_close' ), 9, 2 );
```

That should let the table markup run before the pagination links are added.
