### ISSUE TITLE
Offset and Pagination Do Not Seem to Work Together

### ISSUE THREAD

**Issue by John1John1John** [billerickson/Display-Posts-Pagination#5]
Hi Bill! Thanks for this excellent plugin and add-on!

I seem to be having an issue. I installed the plugin and pagination add-on. But, when I use offset and pagination the pagination is messed up. Below is an example,

[display-posts  offset="4" posts_per_page="4" pagination="true"]

In this test I have 7 posts so the plugin correctly skips the latest 4 posts and displays only the 3 oldest. But, it still displays pagination indicating there are two pages but on page 2 it just shows the same 3 oldest posts.

I would expect it to not display any pagination since there are fewer posts to display than a single page.

Any thoughts on how to address this? Thanks in advance!

**Comment by billerickson** [comment]
That's a great point. The offset parameter breaks the pagination, as it does in WordPress core. It's probably best if we disable pagination if the offset parameter is being used because it won't work anyway.

**Comment by billerickson** [comment]
The most recent code update should fix the issue. Thanks for reporting!
