### ISSUE TITLE
Display Posts Pagination - critical wordpress error

### ISSUE THREAD

**Issue by Jmarcum23** [billerickson/Display-Posts-Pagination#7]
As of today I'm getting a "There has been a critical error on this website." from the display posts pagination and dps templates. If I remove pagination="true" and layout="large" then everything seems to work again. Is there a known error with the current version of WordPress? 

Site = http://www.helpingmehear.com
Page with pagination and dps on = http://www.helpingmehear.com/tinnitus
Page with pagination and dps removed = http://www.helpingmehear.com/hearing-aids

I've deactivated all plugins and reactivated one by one and it appears to be stemming from display posts and display posts pagination. Any help is appreciated. Thanks!

**Comment by billerickson** [comment]
I've tested it with the latest version of WP and have no issues. It's a very simple plugin, only a few lines of code, and nothing that would cause a critical error (that I can think of).

If you can ask your host to share the PHP error log or enable debug mode, we can get some more information on what's causing your issue.

If your host provides a staging environment, you could push a copy of the site to staging and provide me access to it so I can dig in a bit without modifying your live site.

**Comment by Jmarcum23** [comment]
Hi Bill, 

Thank you for the quick response. I downloaded the error log and found it was a deprecated php hook I was using in my dps file. All fixed. Thanks!
