### ISSUE TITLE
Pagination and columns extensions seem to have a display conflict

### ISSUE THREAD

**Issue by hope4greyplaces** [billerickson/Display-Posts-Pagination#8]
Hi, thank you very much for this plugin. I installed both the main plugin and both the pagination and columns extensions, but the pagination links don't see to display as expected. 
Most of my more recent posts have a featured image, and I've set the thumbnail size at 267x150 pixels. When the plugin displays posts with thumbnails in two columns, the pagination links [1, 2, 3,... Next] appear just below the 8th link displayed. Hence, if I display 20 posts, the pagination links appear in the midst of the links and thumbnails. It appears this way regardless of whether excerpts are displayed or not. I don't have this issue if only one column is used. 
I mention the thumbnail size because if I'm on a page where most of the posts don't have a featured image and I choose not to show the excerpt (i.e. it's just links), then the pagination links appear as expected in the bottom right or bottom left. However if I have the excerpts showing then, again, the pagination links appear just beneath the 8th link. If you want to see it in action, I've been trying out the plugin on a test page on my blog here: https://faith.workthegreymatter.com/test/

**Comment by billerickson** [comment]
Try adding the following CSS in Appearance > Customize > Additional CSS:

```
.display-posts-pagination { overflow: hidden; width: 100%; }
```

Thanks

**Comment by hope4greyplaces** [comment]
Thank you very much, that fixed it.
