### ISSUE TITLE
How to install this plugin?

### ISSUE THREAD

**Issue by flarocca** [billerickson/Display-Posts-Pagination#9]
Hi Bill! Your plugin is amazing!! Thanks for that.
I am new at WP and to be honest, and this plugin saved my life!

Now, I came across this extension, but I don't know how to install it.
Do you have any tutorials I can use?

Thanks so much!

**Comment by billerickson** [comment]
You can download the plugin using this link: https://github.com/billerickson/Display-Posts-Pagination/archive/refs/heads/master.zip

Then on your site, go to Plugins > Add New, and click "Upload Plugin" in the top left. Upload the zip file, and click "Activate".

**Comment by jralls** [comment]
You might add that instruction to `Readme.md`.

**Comment by flarocca** [comment]
You are right! I will do it and will send a PR today!
